### PR TITLE
Switch to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by martincostello**
* Switch to GitHub Actions for CI instead of AppVeyor and Travis.
  * Use a stable Id for User Secrets in the sample app for local development. Otherwise it's just a random GUID.

### CODE REVIEW

**Comment by martincostello** [comment]
It's doing that thing where it randomly doesn't build again. Are Actions enabled for this repo?

**Comment by kevinchalet** [comment]
They are 😕 

image

**Comment by martincostello** [comment]
I'll try poking it with a stick again tomorrow then in case there's some voodoo that needs time to settle 😄

**Comment by kevinchalet** [comment]
I had the same issue with the OpenIddict repo. I suppose GitHub Actions doesn't run until at least one workflow is committed to the repo.

Feel free to merge 😃

**Pull request merged**
