### PR TITLE
Attest artifacts

### PR DESCRIPTION
**Pull request by martincostello**
Attest the binaries and packages from the build artifacts.

### CODE REVIEW

**Comment by martincostello** [comment]
@kevinchalet Given we can't use this in OAuth due to file number limits, how would you like to proceed? Would you rather use it here and have the inconsistency, or be consistent and not use it in either?

**Comment by kevinchalet** [comment]
@martincostello let's be consistent 👍🏻

**Comment by martincostello** [comment]
https://github.com/orgs/community/discussions/122028#discussioncomment-9683242

**Comment by kevinchalet** [comment]
Looks good 👍🏻

**Pull request merged**
