### PR TITLE
Update the Steam provider to support the new HTTPS user identifier namespace

### PR DESCRIPTION
**Pull request by kevinchalet**
Fixes https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/43.

Note: this PR will be ported to the 2.0 version.

### CODE REVIEW

**Comment by kevinchalet** [comment]
@shravan2x @Zexuz to avoid having to revert this change if the Steam folks decide to undo their modification, I think it's preferable to support both prefixes.

**Comment by Zexuz** [comment]
Yee, support for both is THE way to go when it comes to steam.

**Comment by shravan2x** [comment]
@PinpointTownes Could you issue a new release on NuGet?

**Comment by kevinchalet** [comment]
Not now. The RTM version will be pushed at the same time as all the aspnet-contrib OAuth2 and OpenID2 providers. And there are still things to do.

In the meantime, use the nightly builds.

**Pull request merged**
