### PR TITLE
Add Steam Blazor Server-Side sample

### PR DESCRIPTION
**Pull request by RestoreMonarchy**
_Summarize the changes this Pull Request makes._
I added another sample for Blazor Server Steam authentication

_If adding a new provider, please ensure you have included appropriate test(s)._
No
_Please include a reference to a GitHub issue if appropriate._
No

### CODE REVIEW

**Comment by RestoreMonarchy** [comment]
It fails on checks cuz it uses .NET Core 3.1

**Comment by kevinchalet** [comment]
@martincostello looks like we didn't update this repository to use a more recent Arcade version like you did for the OAuth 2.0 repo. Is it something we should do as part of the next release?

@RestoreMonarchy thanks for your PR! Correct me if I'm wrong, but the server-side part looks almost identical to the "classical" MVC sample when using server-side Blazor. In this case, I'm not 100% this adds any value (and well... it's code we'd have to maintain in the future).

**Comment by martincostello** [comment]
> @martincostello looks like we didn't update this repository to use a more recent Arcade version like you did for the OAuth 2.0 repo. Is it something we should do as part of the next release?

Sure, I can look at doing this a bit later today.

**Comment by martincostello** [comment]
> > @martincostello looks like we didn't update this repository to use a more recent Arcade version like you did for the OAuth 2.0 repo. Is it something we should do as part of the next release?
> 
> Sure, I can look at doing this a bit later today.

#77

**Comment by martincostello** [comment]
This should build for 3.1 now if you rebase onto the latest changes in the `dev` branch.

**Comment by RestoreMonarchy** [comment]
@kevinchalet 
You're right there isn't much more in this example than in MVC one and I believe you don't want to have another duplicate project to maintain, so I'll just close this PR.
The reason I made is it that I thought I cannot use controllers in server-side Blazor app, but welp of course you can...

**Pull request closed without merging**
