### PR TITLE
Update to ASP.NET Core 3.1

### LINKED ISSUE #74: Some dependencies are too old
Some of the dependencies are too old, such as AngleSharp and Microsoft.IdentityModel.Protocols.

### PR DESCRIPTION
**Pull request by martincostello**
* Update to ASP.NET Core 3.1.
  * Sync various build files' setup with the OAuth project.
  * Update NuGet packages to their latest versions to replace #75 and resolve #74.

See #76.

### CODE REVIEW

**Review by kevinchalet — APPROVED** [review]
🎉

**Comment by martincostello** [comment]
@kevinchalet Just compiling up the release notes, and I notice that with #70 being merged we made a breaking change. Shall I rev the version to 4.0.0?

**Comment by kevinchalet** [comment]
Arf crap, that's not good 😭 
Technically, we have to increase the major version to respect semver, but that means the OpenID and OAuth 2.0 will now have different versions (which is something I wanted to avoid)... not sure what's best.

**Comment by martincostello** [comment]
I can think of 3 options right now:

  1. Change version to 4.0.0
  1. Revert #70 and then re-apply it for a future v4 (or v5) version.
  1. Apply another change on top of this to put Newtonsoft.Json back (as `[Obsolete]`) and populate it from the `JsonDocument`.

**Comment by martincostello** [comment]
Have opened #78 for option 3.

**Pull request merged**
